### ISSUE TITLE
Contribution request

### ISSUE THREAD

**Issue by V01D-NULL** [DacoTaco/StarStruck#18]
Hey guys, love the project!

Played around with something like this on my n3ds and recently bought a wii and decided to see what people are doing with it.

Long story short, I'd like to know how I can help.
Is there a discord server or any means of communication?

Thanks!

**Comment by DacoTaco** [comment]
there is currently no discord server for this specific project, *but* we are in the GC/Wii discord server : https://discord.gg/hKx3FJJgrV

you can find us (Jako and me) in the IOS channel under Wii.
im very much open to contributions and can give you access to the Ghidra server where we are pulling IOS apart
