### ISSUE TITLE
Probable typo in kernel/scheduler/threads.c LaunchRM()

### ISSUE THREAD

**Issue by AndrewPiroli** [DacoTaco/StarStruck#26]
https://github.com/DacoTaco/StarStruck/blob/e67d843f8616668090e1185441e438a88234a660/kernel/source/scheduler/threads.c#L623

The last check in this if statement is  `(elfHeader->e_flags && 0x21) != 0` which will just be optimized 0, it's probably intended to be `(elfHeader->e_flags & 0x21) != 0`.

A slightly more interesting thing is that if you `man 5 elf` 
```
       e_flags
              This  member holds processor-specific flags associated with the file.  Flag names take the form
              EF_`machine_flag'.  Currently, no flags have been defined.
```
So if no flags have been defined by the standard, I'm guessing bit 21 must be a Nintendo specific thing? Is this documented anywhere? A quick search on WiiBrew shows no results.

I only noticed this because of [this comment](https://github.com/DacoTaco/StarStruck/commit/256bc51874c1ba1b796b42edd15324cc83bba81b#r149288586) by @Naim2000 so credit to them :^)

**Comment by DacoTaco** [comment]
nicely spotted !
took a look at ghidra to verify and its indeed a `&` too much :p

![image](https://github.com/user-attachments/assets/8f601eba-0a95-43f8-9681-9208fa3b7f44)

**Comment by DacoTaco** [comment]
fixed in main, thanks @Naim2000 & @AndrewPiroli
